export type Category =
  | "nature"
  | "animals"
  | "travel"
  | "architecture"
  | "people"
  | "fashion"
  | "food"
  | "technology"
  | "business"
  | "sports"
  | "health"
  | "art"
  | "music"
  | "landscape"
  | "city"
  | "interior"
  | "flowers"
  | "cars"
  | "beach"
  | "mountains"
  | "space"
  | "abstract"
  | "minimal"
  | "winter"
  | "summer"
  | "forest"
  | "night"
  | "sunset"
  | "water"
  | "aerial";

export type Orientation = "landscape" | "portrait" | "squarish";
